# Generated by Django 4.2.6 on 2023-10-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2app', '0003_customer_alter_student_email_alter_student_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(blank=True, choices=[(10, 'Yas: 10'), (20, 'Yas: 20'), (30, 'Yas: 30'), (40, 'Yas: 40'), (50, 'Yas: 50')], default=0, null=True),
        ),
    ]
